// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5vkoihMh2Pm2Mzwso2AcRlGp4m9jKq0s',
    appId: '1:557584840561:web:61a749976e05ccac1da8d0',
    messagingSenderId: '557584840561',
    projectId: 'proyecto1-be8a3',
    authDomain: 'proyecto1-be8a3.firebaseapp.com',
    storageBucket: 'proyecto1-be8a3.firebasestorage.app',
    measurementId: 'G-QPGVT5DG86',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClIy849_ejRYvb0S0f7xpIgmlut5gvX48',
    appId: '1:557584840561:android:e3d6a52d07ab1a191da8d0',
    messagingSenderId: '557584840561',
    projectId: 'proyecto1-be8a3',
    storageBucket: 'proyecto1-be8a3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKW_fvKcrE4sUuMpE-GsemNM6RhlOcnCg',
    appId: '1:557584840561:ios:125839f0abacebd71da8d0',
    messagingSenderId: '557584840561',
    projectId: 'proyecto1-be8a3',
    storageBucket: 'proyecto1-be8a3.firebasestorage.app',
    iosBundleId: 'com.example.definitive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKW_fvKcrE4sUuMpE-GsemNM6RhlOcnCg',
    appId: '1:557584840561:ios:125839f0abacebd71da8d0',
    messagingSenderId: '557584840561',
    projectId: 'proyecto1-be8a3',
    storageBucket: 'proyecto1-be8a3.firebasestorage.app',
    iosBundleId: 'com.example.definitive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5vkoihMh2Pm2Mzwso2AcRlGp4m9jKq0s',
    appId: '1:557584840561:web:40f96dd0b098f0361da8d0',
    messagingSenderId: '557584840561',
    projectId: 'proyecto1-be8a3',
    authDomain: 'proyecto1-be8a3.firebaseapp.com',
    storageBucket: 'proyecto1-be8a3.firebasestorage.app',
    measurementId: 'G-7W8KHFM3YH',
  );

}