name: tresde
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  confirm_dialog: ^1.0.4
  url_launcher: ^6.0.20
  flutter:
    sdk: flutter
  model_viewer_plus: ^1.8.0
  file_picker: ^5.0.0
  firebase_core: ^3.9.0
  firebase_storage: ^12.3.7
  cloud_firestore: ^5.6.0
  firebase_auth: ^5.3.4
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true
